import { DocumentType, getModelForClass } from '@typegoose/typegoose';
import { Profile } from './profileModel';
import { File } from '../features/file/schema';
import { Review } from '../features/review/schema';
import { Reservation } from '../features/reservation/schema';
import { Transaction } from '../features/transaction/schema';
import { Cart } from '../features/cart/schema';
import { Order } from '../features/order/schema';
import { Notification } from '../features/notification/schema';
import { Menu } from '../features/menu/schema';
import { Category } from '../features/category/schema';
import { Token } from './token';
import { User } from './userModel';
import { PassportLocalModel } from 'mongoose';

const UserMod = getModelForClass(User);
export type UserModelType = typeof UserMod &
  PassportLocalModel<DocumentType<User>>;
export const UserModel = UserMod as UserModelType;
export const ProfileModel = getModelForClass(Profile);
export const ReviewModel = getModelForClass(Review);
export const ReservationModel = getModelForClass(Reservation);
export const TransactionModel = getModelForClass(Transaction);
export const CartModel = getModelForClass(Cart);
export const OrderModel = getModelForClass(Order);
export const NotificationModel = getModelForClass(Notification);
export const MenuModel = getModelForClass(Menu);
export const CategoryModel = getModelForClass(Category);
export const FileModel = getModelForClass(File);
export const TokenModel = getModelForClass(Token);
